# customer message for prediction
#

std_msgs/Header header

std_msgs/Int16[] predicted_top_left_x
std_msgs/Int16[] predicted_top_left_y
std_msgs/Int16[] predicted_top_right_x
std_msgs/Int16[] predicted_top_right_y
std_msgs/Int16[] predicted_bottom_left_x
std_msgs/Int16[] predicted_bottom_left_y
std_msgs/Int16[] predicted_bottom_right_x
std_msgs/Int16[] predicted_bottom_right_y
std_msgs/Float64[] predicted_distance
std_msgs/Float64[] predicted_yaw
